In [1]:
import os
import sys
import argparse
import pandas as pd
import numpy as np
from glob import glob


In [2]:
project_dir = os.path.abspath('/bgfs/bchandrasekaran/krs228/data/SSP/')
bids_dir    = os.path.join(project_dir, 'data_bids')
behav_dir   = os.path.join('/ix/ahamptonwray/shared/',
                           'ahamptonwray_vah67_jwb103_krs228/',
                           'SSP_MRI_DATA/')
# bids task names
bids_task_list = ['alice', 'badagama']


In [3]:
behav_dir

'/ix/ahamptonwray/shared/ahamptonwray_vah67_jwb103_krs228/SSP_MRI_DATA/'

# task-badagama

In [4]:
task_id = 'BADAGAMA'
bids_task_id = 'badaga'

subject_list = [os.path.basename(x).split('_')[0] for x in sorted(glob(behav_dir+f'/{task_id} fMRI Data/SSP*'))]

In [5]:
behav_dir

'/ix/ahamptonwray/shared/ahamptonwray_vah67_jwb103_krs228/SSP_MRI_DATA/'

In [6]:
new_subject_list = [
                    'SSP096', 'SSP105', 'SSP106', 'SSP107', 'SSP108', 'SSP109', 
                    'SSP110', 'SSP111', 'SSP112', 'SSP113', 'SSP114', 
                   ]

In [7]:
for subject_id in new_subject_list:
    print(subject_id)
    if subject_id=='SSP013':
        filename = sorted(glob(behav_dir + f'/*{task_id}*/{subject_id}*.*'))[1]
    else:
        try:
            filename = sorted(glob(behav_dir + f'/*{task_id}*/{subject_id}*.*'))[0]
        except IndexError:
            print('No files found for', subject_id)
    print('converting ', filename)
    fpath = os.path.join(behav_dir, filename)
    try:
        df = pd.read_csv(fpath)
    except:
        df = pd.read_excel(fpath)
    
    print(df.columns)

    # for task-badagama, single psychopy output that includes all runs
    run_label_num_list = [1, 2, 3] # psychopy variables have this appended to column based on run

    for run_label in run_label_num_list:
        # create a temp dataframe of only trials where sounds were presented
        try:
            print(f'run-{run_label}')
            trial_df = df[df[f'Sound{run_label}'].str.contains('A')==True]

            # fix naming inconsistencies (same normalization cell 9's corrected, one-off SSP001
            # conversion already applies -- some subjects' raw PsychoPy exports use these
            # alternate column names instead of the 'Resp_Block_N.*' / 'Block_N.*' form the
            # rest of this cell assumes)
            # NOTE: renaming the bare 'Block1.'/'Block2.' substring (as originally copied
            # from cell 9) also matches 'Trigger_Block1.*'/'Trigger_Block2.*', but those need
            # to stay in their raw, non-underscored form -- 'tb' below is 'Trigger_Block' (no
            # underscore) for run_label in {1, 2}, matching the raw naming directly. Renaming
            # them out from under 'tb' caused every run-1/run-2 conversion to fail with
            # 'could not process this run' (confirmed 2026-08-07). Scoped to 'Resp_Block*'
            # specifically, which is the only component that actually needs normalizing.
            trial_df.columns = trial_df.columns.str.replace('Resp_Block1_2.', 'Resp_Block_2.')
            trial_df.columns = trial_df.columns.str.replace('Resp_Block1.', 'Resp_Block_1.')
            trial_df.columns = trial_df.columns.str.replace('Resp_Block2.', 'Resp_Block_2.')

            # deal with inconsistent column names
            if run_label==3:
                tb = 'Trigger_Block_'
            else:
                tb = 'Trigger_Block'

            #if len(trial_df)<30:
            #    print('too few trials – incomplete run. Skipping')
            #else:
            start_offset = trial_df[f'{tb}{run_label}.started'].iloc[0]

            ''' Stimulus dataframe '''
            # set up stimulus dataframe
            stim_df = pd.DataFrame(columns=['onset', 
                                            'duration', 
                                            'trial_type',
                                            'stim_file',
                                            'syllable',
                                            'speaker', 
                                            'noise_level'])

            # define onset time (relative to the first stimulus presentation)
            stim_df.onset = trial_df[f'{tb}{run_label}.started'] - start_offset

            # define duration
            stim_df.duration = 0.3

            # define stimulus type (based on sound file – HARDCODED)
            stim_df.trial_type = 'sound'

            # define stimulus soundfile
            stim_df.stim_file   = trial_df[f'Sound{run_label}']
            stim_df.syllable    = trial_df[f'Sound{run_label}'].str.split(pat='.',expand=True)[0].str.split(pat='_',expand=True)[0]
            stim_df.speaker     = trial_df[f'Sound{run_label}'].str.split(pat='.',expand=True)[0].str.split(pat='_',expand=True)[1]
            stim_df.noise_level = trial_df[f'Sound{run_label}'].str.split(pat='.',expand=True)[0].str.split(pat='_',expand=True)[2]

            ''' Response dataframe '''
            # set up response dataframe
            resp_df = pd.DataFrame(columns=['onset', 
                                            'duration',
                                            'response_time', 
                                            'trial_type',
                                            'correct_key',
                                            'response_key'])

            # define onset time (relative to the first stimulus presentation)
            resp_df.onset = trial_df[f'{tb}{run_label}.started'] + trial_df[f'{tb}{run_label}.rt'] - start_offset

            # define duration (arbitrary)
            resp_df.duration = 0.1
            # NOTE: response_time/response_key previously read from '{tb}{run_label}.rt' (the
            # scanner-trigger-wait component -- Trigger_Block_N.keys is only ever 'equal', the
            # trigger pulse key, confirmed by inspecting the raw PsychoPy columns) and a hardcoded
            # np.nan, respectively -- meaning every subject converted through this loop had no
            # usable accuracy at all, and a response_time that wasn't actually measuring the
            # participant's response. The real per-trial response lives in the separate
            # 'Resp_Block_N.*' PsychoPy component (.rt and .keys), matching what the one-off
            # SSP001 fix below (this notebook's cell 9) already does correctly.
            resp_df.response_time = trial_df[f'Resp_Block_{run_label}.rt']
            resp_df.trial_type   = 'response'
            resp_df.correct_key  = trial_df[f'corrAns{run_label}']
            resp_df.response_key = trial_df[f'Resp_Block_{run_label}.keys']

            ''' combine all dataframes '''
            bids_df = pd.concat([stim_df, resp_df], 
                                axis=0, join='outer', 
                                ignore_index=True)
            bids_df.sort_values(by=['onset'], 
                                ignore_index=True,
                                inplace=True)
            try:
                # save to output path
                out_fpath = os.path.join(bids_dir,f'sub-{subject_id}', 'func',
                                         #'~/TEMP_data',
                                         f'sub-{subject_id}_task-{bids_task_id}_run-{run_label:02d}_events.tsv')

                bids_df.to_csv(out_fpath, sep='\t')
                print('saved output to ', out_fpath)
            except FileNotFoundError:
                print(f'no fMRI data for {subject_id}')
        except:
            print('could not process this run')

SSP096
converting  /ix/ahamptonwray/shared/ahamptonwray_vah67_jwb103_krs228/SSP_MRI_DATA/BADAGAMA fMRI Data/SSP096_fMRI_cvcv_PsychoPy_2026-04-18_12h23.22.011.csv
Index(['Sound1', 'corrAns1', 'Jitter', 'B1Loop.thisRepN', 'B1Loop.thisTrialN',
       'B1Loop.thisN', 'B1Loop.thisIndex', 'text.started', 'key_resp.started',
       'Hand.started', 'key_resp.keys', 'key_resp.rt', 'StartTaskText.started',
       'StartTaskResp.started', 'StartTaskResp.keys', 'StartTaskResp.rt',
       'Trigger_Block1.started', 'Block1Hand.started', 'Sound_Block1.started',
       'Resp_Block1.started', 'Resp_Block1.keys', 'Resp_Block1.corr',
       'Resp_Block1.rt', 'Trigger_Block1.keys', 'Trigger_Block1.rt',
       'Acq_Key.started', 'AcqHand.started', 'Acq_Key.keys', 'Acq_Key.rt',
       'Break_Text.started', 'Break_Resp.started', 'participant', 'session',
       'date', 'expName', 'psychopyVersion', 'frameRate', 'Unnamed: 37'],
      dtype='object')
run-1
saved output to  /bgfs/bchandrasekaran/krs228/data/SSP

# Sandbox

In [9]:
subject_id = 'SSP001'
print(subject_id)
filename = sorted(glob(behav_dir + f'/*{task_id}*/{subject_id}*.*'))[0]
print('converting ', filename)
fpath = os.path.join(behav_dir, filename)
try:
    df = pd.read_csv(fpath)
except:
    df = pd.read_excel(fpath)

# for task-badagama, single psychopy output that includes all runs
run_label_num_list = [1, 2, 3] # psychopy variables have this appended to column based on run

for run_label in run_label_num_list:
    # A subject can genuinely be missing a whole run (e.g. sub-SSP001 has no Sound2 column
    # at all -- run-2 behavioral data was never recorded, confirmed separately via the
    # events/BOLD run-count investigation) -- skip gracefully rather than crashing the whole
    # cell (this cell has no per-run try/except, unlike the batch loop above).
    if f'Sound{run_label}' not in df.columns:
        print(f'  no Sound{run_label} column for {subject_id} -- run-{run_label} was never '
             'recorded, skipping.')
        continue

    # create a temp dataframe of only trials where syllables were presented
    trial_df = df[df[f'Sound{run_label}'].str.contains('A')==True]
    
    # fix naming inconsistencies
    trial_df.columns = trial_df.columns.str.replace('Resp_Block1_2.', 'Resp_Block_2.')
    trial_df.columns = trial_df.columns.str.replace('Block1.', 'Block_1.')
    trial_df.columns = trial_df.columns.str.replace('Block2.', 'Block_2.')

    # deal with inconsistent column names
    if run_label==3:
        tb = 'Trigger_Block_'
    else:
        tb = 'Trigger_Block'

    start_offset = trial_df[f'Trigger_Block_{run_label}.started'].iloc[0]

    ''' Stimulus dataframe '''
    # set up stimulus dataframe
    stim_df = pd.DataFrame(columns=['onset', 
                                    'duration', 
                                    'trial_type',
                                    'stim_file',
                                    'syllable',
                                    'speaker', 
                                    'noise_level'])

    # define onset time (relative to the first stimulus presentation)
    stim_df.onset = trial_df[f'Trigger_Block_{run_label}.started'] - start_offset

    # define duration
    stim_df.duration = 0.3

    # define stimulus type (based on sound file – HARDCODED)
    stim_df.trial_type = 'sound'

    # define stimulus soundfile
    stim_df.stim_file   = trial_df[f'Sound{run_label}']
    stim_df.syllable    = trial_df[f'Sound{run_label}'].str.split(pat='.',expand=True)[0].str.split(pat='_',expand=True)[0]
    stim_df.speaker     = trial_df[f'Sound{run_label}'].str.split(pat='.',expand=True)[0].str.split(pat='_',expand=True)[1]
    stim_df.noise_level = trial_df[f'Sound{run_label}'].str.split(pat='.',expand=True)[0].str.split(pat='_',expand=True)[2]

    ''' Response dataframe '''
    # set up response dataframe
    resp_df = pd.DataFrame(columns=['onset', 
                                    'duration',
                                    'response_time', 
                                    'trial_type',
                                    'correct_key',
                                    'response_key'])

    # define onset time (relative to the first stimulus presentation)
    resp_df.onset = (trial_df[f'Trigger_Block_{run_label}.started'] + 
                    trial_df[f'Trigger_Block_{run_label}.rt'] - start_offset)

    # define duration (arbitrary)
    resp_df.duration = 0.1
    resp_df.response_time = trial_df[f'Resp_Block_{run_label}.rt']        
    resp_df.trial_type   = 'response'
    resp_df.correct_key  = trial_df[f'corrAns{run_label}']
    resp_df.response_key = trial_df[f'Resp_Block_{run_label}.keys']
    
    
    ''' combine all dataframes '''
    bids_df = pd.concat([stim_df, resp_df], 
                        axis=0, join='outer', 
                        ignore_index=True)
    bids_df.sort_values(by=['onset'], 
                        ignore_index=True,
                        inplace=True)
    # save to output path
    out_fpath = os.path.join(f'sub-{subject_id}_task-{bids_task_id}_run-{run_label:02d}_events.tsv')

    bids_df.to_csv(out_fpath, sep='\t')
    print('saved output to ', out_fpath)

SSP001
converting  /ix/ahamptonwray/shared/ahamptonwray_vah67_jwb103_krs228/SSP_MRI_DATA/BADAGAMA fMRI Data/SSP001_fMRI_cvcv_PsychoPy_2023-10-19_17h47.15.184.csv
saved output to  sub-SSP001_task-badaga_run-01_events.tsv
  no Sound2 column for SSP001 -- run-2 was never recorded, skipping.
saved output to  sub-SSP001_task-badaga_run-03_events.tsv


In [10]:
trial_df.columns

Index(['Sound1', 'corrAns1', 'Jitter', 'Sound3', 'corrAns3', 'Jitter3',
       'B1Loop.thisRepN', 'B1Loop.thisTrialN', 'B1Loop.thisN',
       'B1Loop.thisIndex', 'B2Loop.thisRepN', 'B2Loop.thisTrialN',
       'B2Loop.thisN', 'B2Loop.thisIndex', 'B3Loop.thisRepN',
       'B3Loop.thisTrialN', 'B3Loop.thisN', 'B3Loop.thisIndex', 'text.started',
       'key_resp.started', 'Hand.started', 'key_resp.keys', 'key_resp.rt',
       'StartTaskText.started', 'StartTaskResp.started', 'StartTaskResp.keys',
       'StartTaskResp.rt', 'Trigger_Block_1.started', 'Block1Hand.started',
       'Sound_Block_1.started', 'Resp_Block_1.started', 'Resp_Block_1.keys',
       'Resp_Block_1.corr', 'Resp_Block_1.rt', 'Trigger_Block_1.keys',
       'Trigger_Block_1.rt', 'Acq_Key.started', 'AcqHand.started',
       'Acq_Key.keys', 'Acq_Key.rt', 'Break_Text.started',
       'Break_Resp.started', 'Break_Resp.keys', 'Break_Resp.rt',
       'Break_Text_Ready.started', 'Break_Resp_Ready.started',
       'Break_Resp_Ready

In [11]:
trial_df['key_resp.keys'].unique()

array([nan], dtype=object)

In [12]:
run3_columns = trial_df.columns[trial_df.columns.str.contains('3')]

In [13]:
trial_df[run3_columns]

,Sound3,corrAns3,Jitter3,B3Loop.thisRepN,B3Loop.thisTrialN,B3Loop.thisN,B3Loop.thisIndex,Trigger_Block_3.started,Block3Hand.started,Sound_Block_3.started,Resp_Block_3.started,Resp_Block_3.keys,Resp_Block_3.corr,Resp_Block_3.rt,Trigger_Block_3.keys,Trigger_Block_3.rt
186,DA_M1_n2.wav,3.0,0.192,0.0,0.0,0.0,32.0,872.140690,872.140690,0.199080,0.199080,8.0,0.0,1.329808,equal,1.897553
187,MA_M1_0.wav,5.0,0.205,0.0,1.0,1.0,70.0,874.884555,874.884555,0.214598,0.214598,NaN,0.0,NaN,equal,1.163285
188,MA_M1_n6.wav,5.0,0.124,0.0,2.0,2.0,73.0,876.903851,876.903851,0.131552,0.131552,NaN,0.0,NaN,equal,1.134295
189,BA_F1_8.wav,2.0,0.068,0.0,3.0,3.0,1.0,878.879750,878.879750,0.080754,0.080754,8.0,0.0,1.047406,equal,1.158562
190,BA_F1_0.wav,2.0,0.110,0.0,4.0,4.0,0.0,880.888102,880.888102,0.112826,0.112826,8.0,0.0,1.054711,equal,1.158304
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
361,GA_M1_Q.wav,4.0,0.200,1.0,85.0,175.0,54.0,1222.889324,1222.889324,0.213665,0.213665,NaN,0.0,NaN,equal,1.156166
362,MA_M2_n2.wav,5.0,0.062,1.0,86.0,176.0,77.0,1224.906096,1224.906096,0.063540,0.063540,NaN,0.0,NaN,equal,1.131413
363,BA_M2_Q.wav,2.0,0.070,1.0,87.0,177.0,19.0,1226.890932,1226.890932,0.081859,0.081859,NaN,0.0,NaN,equal,1.154551
364,GA_F1_Q.wav,4.0,0.097,1.0,88.0,178.0,44.0,1228.894979,1228.894979,0.096524,0.096524,NaN,0.0,NaN,equal,1.143411


In [14]:
trial_df['Trigger_Block_3.keys'].unique()

array(['equal'], dtype=object)

In [15]:
trial_df['Resp_Block_3.keys'].unique()

array([ 8., nan,  9.,  7.])

In [16]:
trial_df['Resp_Block_3.keys'].unique()

array([ 8., nan,  9.,  7.])

In [17]:
trial_df['Resp_Block_3.corr'].unique()

array([0.])

In [18]:
trial_df['Resp_Block_3.rt'].unique()

array([1.3298081,       nan, 1.0474062, 1.0547107, 0.6197368, 0.8932068,
       0.6895839, 0.9849272, 0.9739847, 0.7078062, 0.6513816, 0.7491013,
       1.0304709, 0.0434385, 0.8510457, 0.7932976, 0.895842 , 0.9031593,
       0.8076936, 0.9932042, 0.6844052, 0.6839135, 0.9857109, 0.8200603,
       0.8133813, 1.0246879, 0.9593445, 0.0293062, 1.0248787, 0.9182919,
       0.9802152, 0.9319746, 1.0293112, 1.066655 , 1.0348732, 0.8923079,
       0.9191704, 0.7885943, 0.8402384, 1.0491882, 0.889211 , 0.7874545,
       0.8917683, 0.8755338, 1.0789863, 0.8597869, 0.7557642, 1.072958 ,
       0.6515225, 0.9978234])

In [ ]:
sorted(os.listdir(os.path.join(behav_dir, 'BADAGAMA fMRI Data')))