In [1]:
import os
import sys
import argparse
import pandas as pd
import numpy as np
from glob import glob


In [2]:
project_dir = os.path.abspath('/bgfs/bchandrasekaran/krs228/data/SSP/')
bids_dir    = os.path.join(project_dir, 'data_bids')
behav_dir   = os.path.join('/ix/ahamptonwray/shared/',
                           'ahamptonwray_vah67_jwb103_krs228/',
                           'SSP_MRI_DATA/')
# bids task names
bids_task_list = ['alice', 'badagama']


In [3]:
behav_dir

'/ix/ahamptonwray/shared/ahamptonwray_vah67_jwb103_krs228/SSP_MRI_DATA/'

# task-badagama

In [4]:
task_id = 'BADAGAMA'
bids_task_id = 'badaga'

subject_list = [os.path.basename(x).split('_')[0] for x in sorted(glob(behav_dir+f'/{task_id} fMRI Data/SSP*'))]

In [5]:
behav_dir

'/ix/ahamptonwray/shared/ahamptonwray_vah67_jwb103_krs228/SSP_MRI_DATA/'

In [6]:
new_subject_list = [
                    'SSP096', 'SSP105', 'SSP106', 'SSP107', 'SSP108', 'SSP109', 
                    'SSP110', 'SSP111', 'SSP112', 'SSP113', 'SSP114', 
                   ]

In [9]:
for subject_id in new_subject_list:
    print(subject_id)
    if subject_id=='SSP013':
        filename = sorted(glob(behav_dir + f'/*{task_id}*/{subject_id}*.*'))[1]
    else:
        try:
            filename = sorted(glob(behav_dir + f'/*{task_id}*/{subject_id}*.*'))[0]
        except IndexError:
            print('No files found for', subject_id)
    print('converting ', filename)
    fpath = os.path.join(behav_dir, filename)
    try:
        df = pd.read_csv(fpath)
    except:
        df = pd.read_excel(fpath)
    
    print(df.columns)

    # for task-badagama, single psychopy output that includes all runs
    run_label_num_list = [1, 2, 3] # psychopy variables have this appended to column based on run

    for run_label in run_label_num_list:
        # create a temp dataframe of only trials where sounds were presented
        try:
            print(f'run-{run_label}')
            trial_df = df[df[f'Sound{run_label}'].str.contains('A')==True]

            # fix naming inconsistencies (same normalization cell 9's corrected, one-off SSP001
            # conversion already applies -- some subjects' raw PsychoPy exports use these
            # alternate column names instead of the 'Resp_Block_N.*' / 'Block_N.*' form the
            # rest of this cell assumes)
            # NOTE: renaming the bare 'Block1.'/'Block2.' substring (as originally copied
            # from cell 9) also matches 'Trigger_Block1.*'/'Trigger_Block2.*', but those need
            # to stay in their raw, non-underscored form -- 'tb' below is 'Trigger_Block' (no
            # underscore) for run_label in {1, 2}, matching the raw naming directly. Renaming
            # them out from under 'tb' caused every run-1/run-2 conversion to fail with
            # 'could not process this run' (confirmed 2026-08-07). Scoped to 'Resp_Block*'
            # specifically, which is the only component that actually needs normalizing.
            trial_df.columns = trial_df.columns.str.replace('Resp_Block1_2.', 'Resp_Block_2.')
            trial_df.columns = trial_df.columns.str.replace('Resp_Block1.', 'Resp_Block_1.')
            trial_df.columns = trial_df.columns.str.replace('Resp_Block2.', 'Resp_Block_2.')

            # deal with inconsistent column names
            if run_label==3:
                tb = 'Trigger_Block_'
            else:
                tb = 'Trigger_Block'

            #if len(trial_df)<30:
            #    print('too few trials – incomplete run. Skipping')
            #else:
            start_offset = trial_df[f'{tb}{run_label}.started'].iloc[0]

            ''' Stimulus dataframe '''
            # set up stimulus dataframe
            stim_df = pd.DataFrame(columns=['onset', 
                                            'duration', 
                                            'trial_type',
                                            'stim_file',
                                            'syllable',
                                            'speaker', 
                                            'noise_level'])

            # define onset time (relative to the first stimulus presentation)
            stim_df.onset = trial_df[f'{tb}{run_label}.started'] - start_offset

            # define duration
            stim_df.duration = 0.3

            # define stimulus type (based on sound file – HARDCODED)
            stim_df.trial_type = 'sound'

            # define stimulus soundfile
            stim_df.stim_file   = trial_df[f'Sound{run_label}']
            stim_df.syllable    = trial_df[f'Sound{run_label}'].str.split(pat='.',expand=True)[0].str.split(pat='_',expand=True)[0]
            stim_df.speaker     = trial_df[f'Sound{run_label}'].str.split(pat='.',expand=True)[0].str.split(pat='_',expand=True)[1]
            stim_df.noise_level = trial_df[f'Sound{run_label}'].str.split(pat='.',expand=True)[0].str.split(pat='_',expand=True)[2]

            ''' Response dataframe '''
            # set up response dataframe
            resp_df = pd.DataFrame(columns=['onset', 
                                            'duration',
                                            'response_time', 
                                            'trial_type',
                                            'correct_key',
                                            'response_key'])

            # define onset time (relative to the first stimulus presentation)
            resp_df.onset = trial_df[f'{tb}{run_label}.started'] + trial_df[f'{tb}{run_label}.rt'] - start_offset

            # define duration (arbitrary)
            resp_df.duration = 0.1
            # NOTE: response_time/response_key previously read from '{tb}{run_label}.rt' (the
            # scanner-trigger-wait component -- Trigger_Block_N.keys is only ever 'equal', the
            # trigger pulse key, confirmed by inspecting the raw PsychoPy columns) and a hardcoded
            # np.nan, respectively -- meaning every subject converted through this loop had no
            # usable accuracy at all, and a response_time that wasn't actually measuring the
            # participant's response. The real per-trial response lives in the separate
            # 'Resp_Block_N.*' PsychoPy component (.rt and .keys), matching what the one-off
            # SSP001 fix below (this notebook's cell 9) already does correctly.
            resp_df.response_time = trial_df[f'Resp_Block_{run_label}.rt']
            resp_df.trial_type   = 'response'
            resp_df.correct_key  = trial_df[f'corrAns{run_label}']
            resp_df.response_key = trial_df[f'Resp_Block_{run_label}.keys']

            ''' combine all dataframes '''
            bids_df = pd.concat([stim_df, resp_df], 
                                axis=0, join='outer', 
                                ignore_index=True)
            bids_df.sort_values(by=['onset'], 
                                ignore_index=True,
                                inplace=True)
            try:
                # save to output path
                out_fpath = os.path.join(bids_dir,f'sub-{subject_id}', 'func',
                                         #'~/TEMP_data',
                                         f'sub-{subject_id}_task-{bids_task_id}_run-{run_label:02d}_events.tsv')

                bids_df.to_csv(out_fpath, sep='\t')
                print('saved output to ', out_fpath)
            except FileNotFoundError:
                print(f'no fMRI data for {subject_id}')
        except:
            print('could not process this run')

SSP096
converting  /ix/ahamptonwray/shared/ahamptonwray_vah67_jwb103_krs228/SSP_MRI_DATA/BADAGAMA fMRI Data/SSP096_fMRI_cvcv_PsychoPy_2026-04-18_12h23.22.011.csv
Index(['Sound1', 'corrAns1', 'Jitter', 'B1Loop.thisRepN', 'B1Loop.thisTrialN',
       'B1Loop.thisN', 'B1Loop.thisIndex', 'text.started', 'key_resp.started',
       'Hand.started', 'key_resp.keys', 'key_resp.rt', 'StartTaskText.started',
       'StartTaskResp.started', 'StartTaskResp.keys', 'StartTaskResp.rt',
       'Trigger_Block1.started', 'Block1Hand.started', 'Sound_Block1.started',
       'Resp_Block1.started', 'Resp_Block1.keys', 'Resp_Block1.corr',
       'Resp_Block1.rt', 'Trigger_Block1.keys', 'Trigger_Block1.rt',
       'Acq_Key.started', 'AcqHand.started', 'Acq_Key.keys', 'Acq_Key.rt',
       'Break_Text.started', 'Break_Resp.started', 'participant', 'session',
       'date', 'expName', 'psychopyVersion', 'frameRate', 'Unnamed: 37'],
      dtype='object')
run-1
saved output to  /bgfs/bchandrasekaran/krs228/data/SSP

# Sandbox

In [80]:
subject_id = 'SSP001'
print(subject_id)
filename = sorted(glob(behav_dir + f'/*{task_id}*/{subject_id}*.*'))[0]
print('converting ', filename)
fpath = os.path.join(behav_dir, filename)
try:
    df = pd.read_csv(fpath)
except:
    df = pd.read_excel(fpath)

# for task-badagama, single psychopy output that includes all runs
run_label_num_list = [1, 2, 3] # psychopy variables have this appended to column based on run

for run_label in run_label_num_list:
    # create a temp dataframe of only trials where syllables were presented
    trial_df = df[df[f'Sound{run_label}'].str.contains('A')==True]
    
    # fix naming inconsistencies
    trial_df.columns = trial_df.columns.str.replace('Resp_Block1_2.', 'Resp_Block_2.')
    trial_df.columns = trial_df.columns.str.replace('Block1.', 'Block_1.')
    trial_df.columns = trial_df.columns.str.replace('Block2.', 'Block_2.')

    # deal with inconsistent column names
    if run_label==3:
        tb = 'Trigger_Block_'
    else:
        tb = 'Trigger_Block'

    start_offset = trial_df[f'Trigger_Block_{run_label}.started'].iloc[0]

    ''' Stimulus dataframe '''
    # set up stimulus dataframe
    stim_df = pd.DataFrame(columns=['onset', 
                                    'duration', 
                                    'trial_type',
                                    'stim_file',
                                    'syllable',
                                    'speaker', 
                                    'noise_level'])

    # define onset time (relative to the first stimulus presentation)
    stim_df.onset = trial_df[f'Trigger_Block_{run_label}.started'] - start_offset

    # define duration
    stim_df.duration = 0.3

    # define stimulus type (based on sound file – HARDCODED)
    stim_df.trial_type = 'sound'

    # define stimulus soundfile
    stim_df.stim_file   = trial_df[f'Sound{run_label}']
    stim_df.syllable    = trial_df[f'Sound{run_label}'].str.split(pat='.',expand=True)[0].str.split(pat='_',expand=True)[0]
    stim_df.speaker     = trial_df[f'Sound{run_label}'].str.split(pat='.',expand=True)[0].str.split(pat='_',expand=True)[1]
    stim_df.noise_level = trial_df[f'Sound{run_label}'].str.split(pat='.',expand=True)[0].str.split(pat='_',expand=True)[2]

    ''' Response dataframe '''
    # set up response dataframe
    resp_df = pd.DataFrame(columns=['onset', 
                                    'duration',
                                    'response_time', 
                                    'trial_type',
                                    'correct_key',
                                    'response_key'])

    # define onset time (relative to the first stimulus presentation)
    resp_df.onset = (trial_df[f'Trigger_Block_{run_label}.started'] + 
                    trial_df[f'Trigger_Block_{run_label}.rt'] - start_offset)

    # define duration (arbitrary)
    resp_df.duration = 0.1
    resp_df.response_time = trial_df[f'Resp_Block_{run_label}.rt']        
    resp_df.trial_type   = 'response'
    resp_df.correct_key  = trial_df[f'corrAns{run_label}']
    resp_df.response_key = trial_df[f'Resp_Block_{run_label}.keys']
    
    
    ''' combine all dataframes '''
    bids_df = pd.concat([stim_df, resp_df], 
                        axis=0, join='outer', 
                        ignore_index=True)
    bids_df.sort_values(by=['onset'], 
                        ignore_index=True,
                        inplace=True)
    # save to output path
    out_fpath = os.path.join(f'sub-{subject_id}_task-{bids_task_id}_run-{run_label:02d}_events.tsv')

    bids_df.to_csv(out_fpath, sep='\t')
    print('saved output to ', out_fpath)

SSP086
converting  /ix/ahamptonwray/shared/ahamptonwray_vah67_jwb103_krs228/SSP_MRI_DATA/BADAGAMA fMRI Data/SSP086_fMRI_cvcv_PsychoPy_2025-05-25_15h54.23.733.xlsx
saved output to  sub-SSP086_task-badaga_run-01_events.tsv
saved output to  sub-SSP086_task-badaga_run-02_events.tsv
saved output to  sub-SSP086_task-badaga_run-03_events.tsv


In [81]:
trial_df.columns

Index(['Sound1', 'corrAns1', 'Jitter', 'Sound2', 'corrAns2', 'Jitter2',
       'Sound3', 'corrAns3', 'Jitter3', 'B1Loop.thisRepN', 'B1Loop.thisTrialN',
       'B1Loop.thisN', 'B1Loop.thisIndex', 'B2Loop.thisRepN',
       'B2Loop.thisTrialN', 'B2Loop.thisN', 'B2Loop.thisIndex',
       'B3Loop.thisRepN', 'B3Loop.thisTrialN', 'B3Loop.thisN',
       'B3Loop.thisIndex', 'text.started', 'key_resp.started', 'Hand.started',
       'key_resp.keys', 'key_resp.rt', 'StartTaskText.started',
       'StartTaskResp.started', 'StartTaskResp.keys', 'StartTaskResp.rt',
       'Trigger_Block_1.started', 'Block1Hand.started',
       'Sound_Block_1.started', 'Resp_Block_1.started', 'Resp_Block_1.keys',
       'Resp_Block_1.corr', 'Trigger_Block_1.keys', 'Trigger_Block_1.rt',
       'Acq_Key.started', 'AcqHand.started', 'Acq_Key.keys', 'Resp_Block_1.rt',
       'Acq_Key.rt', 'Break_Text.started', 'Break_Resp.started',
       'Break_Resp.keys', 'Break_Resp.rt', 'Break_Text_Ready.started',
       'Break_Resp_

In [82]:
trial_df['key_resp.keys'].unique()

array([nan], dtype=object)

In [93]:
run3_columns = trial_df.columns[trial_df.columns.str.contains('3')]

In [94]:
trial_df[run3_columns]

,Sound3,corrAns3,Jitter3,B3Loop.thisRepN,B3Loop.thisTrialN,B3Loop.thisN,B3Loop.thisIndex,Trigger_Block_3.started,Block3Hand.started,Sound_Block_3.started,Resp_Block_3.started,Resp_Block_3.keys,Resp_Block_3.corr,Resp_Block_3.rt,Trigger_Block_3.keys,Trigger_Block_3.rt
366,DA_F1_n2.wav,3.0,0.085,0.0,0.0,0.0,22.0,866.272560,866.272560,0.098692,0.098692,9.0,0.0,1.792583,equal,1.933423
367,BA_M1_0.wav,2.0,0.180,0.0,1.0,1.0,10.0,869.053132,869.053132,0.179438,0.179438,NaN,0.0,NaN,equal,1.152996
368,MA_M1_0.wav,5.0,0.205,0.0,2.0,2.0,70.0,871.049570,871.049570,0.212828,0.212828,NaN,0.0,NaN,equal,1.155718
370,DA_M2_n2.wav,3.0,0.197,0.0,4.0,4.0,37.0,875.045930,875.045930,0.212032,0.212032,NaN,0.0,NaN,equal,1.159364
371,DA_F1_0.wav,3.0,0.188,0.0,5.0,5.0,20.0,877.048670,877.048670,0.195770,0.195770,NaN,0.0,NaN,equal,1.157067
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
541,BA_M2_Q.wav,2.0,0.070,1.0,85.0,175.0,19.0,1217.051343,1217.051343,0.079514,0.079514,NaN,0.0,NaN,equal,1.155535
542,GA_F2_0.wav,4.0,0.188,1.0,86.0,176.0,45.0,1219.052897,1219.052897,0.197527,0.197527,NaN,0.0,NaN,equal,1.152870
543,MA_F1_Q.wav,5.0,0.066,1.0,87.0,177.0,64.0,1221.042255,1221.042255,0.078585,0.078585,NaN,0.0,NaN,equal,1.163207
544,GA_F1_Q.wav,4.0,0.097,1.0,88.0,178.0,44.0,1223.055761,1223.055761,0.112692,0.112692,6.0,0.0,0.315734,equal,1.150623


In [83]:
trial_df['Trigger_Block_3.keys'].unique()

array(['equal'], dtype=object)

In [84]:
trial_df['Resp_Block_3.keys'].unique()

array([ 9., nan,  8.,  7.,  6.])

In [84]:
trial_df['Resp_Block_3.keys'].unique()

array([ 9., nan,  8.,  7.,  6.])

In [85]:
trial_df['Resp_Block_3.corr'].unique()

array([0.])

In [86]:
trial_df['Resp_Block_3.rt'].unique()

array([1.7925832,       nan, 1.0230332, 0.4339809, 1.0217307, 0.2630648,
       0.0549591, 0.0542536, 0.3007567, 0.5173215, 0.0274305, 0.140964 ,
       0.4471324, 0.3271938, 0.1819879, 0.9037122, 0.892818 , 0.0593214,
       0.8676115, 0.0196822, 0.9858996, 1.015925 , 0.8593543, 0.890994 ,
       0.5039477, 0.1172675, 0.5249465, 0.1383863, 0.605198 , 0.8660574,
       0.3753802, 0.9253178, 1.0731309, 0.3157339])

In [13]:
sorted(os.listdir(os.path.join(behav_dir, 'BADAGAMA fMRI Data')))

['.~lock.SSP009_fMRI_cvcv_PsychoPy_2024-01-02_13h30.17.461.csv#',
 'Badagama_fMRI_AccRT.xlsx',
 'Badagama_fMRI_Clean.xlsx',
 'SSP001_fMRI_cvcv_PsychoPy_2023-10-19_17h47.15.184.csv',
 'SSP002_fMRI_cvcv_PsychoPy_2023-10-28_11h03.22.491.csv',
 'SSP005_fMRI_cvcv_PsychoPy_2023-09-25_10h18.59.870.csv',
 'SSP008_fMRI_cvcv_PsychoPy_2024-06-02_16h32.52.157.csv',
 'SSP009_fMRI_cvcv_PsychoPy_2024-01-02_13h30.17.461.csv',
 'SSP011_fMRI_cvcv_PsychoPy_2024-01-28_16h24.40.740.csv',
 'SSP012_fMRI_cvcv_PsychoPy_2023-11-06_10h29.02.354.csv',
 'SSP012_fMRI_cvcv_PsychoPy_2023-11-06_10h51.31.569.csv',
 'SSP013_fMRI_cvcv_PsychoPy_2023-11-28_17h48.12.375.csv',
 'SSP013_fMRI_cvcv_PsychoPy_2023-11-28_17h51.26.292.csv',
 'SSP014_fMRI_cvcv_PsychoPy_2023-11-08_16h54.21.548.csv',
 'SSP015_fMRI_cvcv_PsychoPy_2024-04-25_17h49.16.992.csv',
 'SSP017_fMRI_cvcv_PsychoPy_2024-03-03_15h57.22.157.csv',
 'SSP018_fMRI_cvcv_PsychoPy_2023-12-07_17h14.51.573.csv',
 'SSP020_fMRI_cvcv_PsychoPy_2023-11-11_15h53.29.156.csv',
 'SSP0